### ISSUE TITLE
Use of `dispatch` requires explicit use of `hop(to:)`

### ISSUE THREAD

**Issue by madsodgaard** [vapor-community/jobs-redis-driver#23]
Currently, when you dispatch a job inside a route handler or another context you can run into a NIO precondition that the dispatch method is not returning on the same event loop. This happens due to `_QueuesRedisDriver` using a `client` property, which is basically `RedisConnectionPool` which could be on any of `app.eventLoopGroup`'s event loops.

Even though `_QueuesRedisDriver` conforms to `RedisClient` and has a `eventLoop` property, it still uses `client` to send the request, which means it ends up on the pool's event loop, causing the precondition.

An easy fix is adding `.hop(to:)` whenever you use `.dispatch()` for example. However, this can get tedious to remember. So, this package or `RedisStack` should handle hopping to the `context.eventLoop` automatically

**Comment by jdmcd** [comment]
@madsodgaard very good catch here, thanks for bringing it up. Just to be clear, are you talking about lines like this https://github.com/vapor/queues-redis-driver/blob/master/Sources/QueuesRedisDriver/JobsRedisDriver.swift#L106 should be using `hop(to:)`?

**Comment by madsodgaard** [comment]
@jdmcd Yup! The subscription methods should probably hop to the context event loop as well.

**Comment by jdmcd** [comment]
@madsodgaard returning to this since I think this is going to start affecting my app soon. When you say `hop(to:)` needs to be used what would we be hopping to? Something like `.hop(to: client.eventLoop)`? Or something else?

**Comment by madsodgaard** [comment]
@jdmcd Right now it's returning on the `client.eventLoop` which could be any event loop of the group, so we need to hop to `context.eventLoop` which for example is the `Request` event loop. I actually think we could fix this by just overriding `RedisClient.eventLoop` on `_QueuesRedisQueue`, otherwise we'd add `.hop(to: context.eventLoop)` to `_QueuesRedisQueue.send()` (not sure if we need the other helper functions as well)

```swift
extension _QueuesRedisQueue: RedisClient {
  ...

  var eventLoop: EventLoop {
    self.context.eventLoop
  }
}
```

**Comment by Andrewangeta** [comment]
@madsodgaard Yea this would definitely work. All the redis commands use the client/pools event loop to do its work so overriding the `_QueuesRedisQueue` to do it would just switch all the event loops being used to be the `context`'s loop since it's conforming to the protocol. Just went through to verify that all commands had an event loop etc.
