### ISSUE TITLE
Remove 4.0.0 tag

### ISSUE THREAD

**Issue by kaishin** [vapor-community/jobs-redis-driver#29]
Not sure if I am missing something, but there is a `4.0.0` tag that doesn't seem to fit semver. This causes scripts and tools that check for outdated versions to suggest updating to `4.0.0`.

**Comment by jdmcd** [comment]
Hmm good catch, thanks @kaishin. @0xTim @gwynne what is the protocol for something like this here theoretically someone could be relying on the 4.0.0 tag? (But would be really strange if they were since it's not a published release)

**Comment by gwynne** [comment]
In a case like this, just remove the tag. Anyone who was incorrectly relying on it is unfortunately out of luck; there isn't really a better option.

**Comment by 0xTim** [comment]
Concur

**Comment by jdmcd** [comment]
Perfect - will do. Thanks @kaishin!

**Comment by kaishin** [comment]
Thanks for the quick resolution!
