### ISSUE TITLE
Heroku Redis version 7.0.10

### ISSUE THREAD

**Issue by jake-betplusev** [vapor-community/jobs-redis-driver#37]
### Describe the bug

I upgraded to Heroku Redis version 7.0.10 and am now getting the following error:

```
Swift/ErrorType.swift:200: Fatal error: Error raised at top level:
QueuesRedisDriver.InvalidRedisURL(url: "my-heroku-redis-instance")
```

Any help would be greatly appreciated 🙏

**Comment by 0xTim** [comment]
@jake-betplusev are you 100% sure the url you're providing is a valid URL for Redis? That's the only reason that should throw that error

**Comment by jake-betplusev** [comment]
Thanks for the reply @0xTim ! 

This was resolved with time. The Redis instance must not have been available immediately after the migration. 

Apologies for not following up and closing.

**Comment by 0xTim** [comment]
Glad to hear it's working!
